=== MatiasAGomezJ/LLMM/Bloc3/Activitat4Bloc3/apartado2/persones.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="persones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1" />
                                        <xs:maxLength value="15" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="llinatge" type="xs:string" minOccurs="0"></xs:element>
                            <xs:element name="edat" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1" />
                                        <xs:maxInclusive value="99" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="data_naixement" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="poblaciÃ³" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sexe" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MatiasAGomezJ/LLMM/Bloc3/Activitat4Bloc3/apartado2/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<persones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persones.xsd">
    <persona sexe="dona">
        <nom>Inés</nom>
        <llinatge>Ruíz</llinatge>
        <edat>36</edat>
        <data_naixement població="Madrid">3-10-1985</data_naixement>
    </persona>
    <persona>
        <llinatge>Pons</llinatge>
        <edat>45</edat>
        <data_naixement població="Palma">3-10-1979</data_naixement>
    </persona>
</persones>
